Game state
marmelab/kuba-mobile pull request #2
Opened 2021-09-20 13:57 UTC by arimet

2021-09-20 14:35 UTC, fzaninotto commented on app.config.ts
> +          API_URL: 'kittens are cool',
I prefer that you use process.env.API_URL

2021-09-20 16:25 UTC, Aherbeth commented on src/GameState/Board.tsx
> +                  &#x2022;
as we said, we have to try a css based or a image based Marble

2021-09-21 09:44 UTC, alexisjanvier commented
@arimet need rebase

2021-09-21 15:02 UTC, Aherbeth approved these changes

2021-09-22 07:11 UTC, alexisjanvier requested changes

2021-09-22 07:11 UTC, alexisjanvier commented on .env.sample
> +API_URL = http://192.168.86.165:3000
Please, explain in the `readme` file what to do with this file.

2021-09-22 07:11 UTC, alexisjanvier commented on App.tsx
> +  Home: undefined;
If it is `undefined`, why declare it?
(Also, I find it confusing because you import a `GameSelector` for example and then you're claim it as `undefined` in this `RootStackParamList`...)

2021-09-22 07:11 UTC, alexisjanvier commented on app.config.ts
> +  slug: 'kuba-mobile',
What is the purpose of a `slug` in a mobile application?

2021-09-22 07:11 UTC, alexisjanvier commented on package.json
> +    "expo-linear-gradient": "~9.2.0",
I'm noting this because I've noticed it several times now, but I'm not a fan of mixing up the version control tagging of dependencies (`` or `^` or `~`)

2021-09-22 07:11 UTC, alexisjanvier commented on src/GameSelector/index.tsx
> +      console.error('Validation Failed');
Do you still need this?

2021-09-22 07:11 UTC, alexisjanvier commented on src/GameState/Marble.tsx
> +  const size = props.size || props.value === 0 ? 4 : 10;
I find this `props.value === 0 ? 4 : 10` a bit strange. The condition is that either we take the size of the `props.size`, or if `props.value` is equal to 0 we take a size of 4, otherwise the size is 10 ... Isn't that a bit complicated?

2021-09-22 07:11 UTC, alexisjanvier commented on src/GameState/index.tsx
> +  return { ...state, [action.type]: action.value };
I know it's more verbose, but I like it when action types are explicit. Here, I understand the logic of `type = "game"` to directly modify your state. 
But first of all, if your reducer gets complicated, you'll have to keep some of the logic handling the new values outside the reducer.
And furthermore, I find it much less readable. For example, a `type = "gameInitialization"` seems to me to make the code easier to understand.

2021-09-22 07:11 UTC, alexisjanvier commented on src/GameState/index.tsx
> +      console.error(error);
Is there no impact on the interface in this case?

2021-09-22 07:11 UTC, alexisjanvier commented on src/GameState/index.tsx
> +          {state.players.map((player) => {
```
{state.players.map((player) => (
     <GameUser user={getPlayerObject(player)} key={player.id} />;
))}
```
it doesn't work in react-native?

2021-09-22 07:47 UTC, arimet commented on App.tsx
> +  Home: undefined;
I followed the documentation of react navigation : https://reactnavigation.org/docs/typescript/
Specifying undefined means that the route doesn't have params.

2021-09-22 07:52 UTC, arimet commented on app.config.ts
> +  slug: 'kuba-mobile',
The slug is the word used by expo to define a sharing url via expo community

2021-09-22 07:53 UTC, arimet commented on src/GameState/Marble.tsx
> +  const size = props.size || props.value === 0 ? 4 : 10;
I agree, in the associate PR that comes right after, I changed this logic!

2021-09-22 08:16 UTC, arimet commented on package.json
> +    "expo-linear-gradient": "~9.2.0",
I am not familiar with the best practices on version control.

2021-09-22 08:51 UTC, alexisjanvier approved these changes
Non-blocking remarks that may or may not be taken into account later

2021-09-22 08:51 UTC, alexisjanvier commented on README.md
> +This file must contain a variable `API_URL` which is the address of your data provider
You can use the `.env.sample` file as a starting point by renaming it `.env`

2021-09-22 08:51 UTC, alexisjanvier commented on src/GameState/index.tsx
> +  state: GameInitialization,
That wasn't really the point of my comment... I was talking more about something like 

```javascript
const GAME_INITIALIZATION = 'gameInitialization';
const reducer = (
  state: DefaultState,
  action: { type: string; value: any },
) => {
    switch (action.type) {
        case GAME_INITIALIZATION:
            return { ...state, game: action.value };
        default:
            return state;
    }
};
```

Then

```javascript
const initGame = game => dispatch({ type: GAME_INITIALIZATION, value: game });
```

But **if necessary** you can do it later

2021-09-22 08:57 UTC, alexisjanvier commented on package.json
> +    "expo-linear-gradient": "~9.2.0",
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies

Personally, I fix the versions (and I added a `save-exact=true` in my `~/.npmrc` file)

2021-09-22 08:58 UTC, alexisjanvier approved these changes

2021-09-22 09:00 UTC, merged