Add Websocket to GameState component.
marmelab/kuba-mobile pull request #6
Opened 2021-09-22 13:08 UTC by arimet

Implementation of websocket to display in real time our game board

2021-09-22 14:40 UTC, alexisjanvier requested changes

2021-09-22 14:40 UTC, alexisjanvier commented on src/GameState/index.tsx
> +let WS: any = undefined;
Why do you need to declare `WS` outside the `GameState` method?

2021-09-22 14:40 UTC, alexisjanvier commented on src/GameState/index.tsx
> +    initWebSocket();
To close your websocket, you must do it as return of your useEffect.

```javascript
useEffect(() => {
    getGame();
    initWebSocket();
    return () => {
        if (WS) WS.close();
     };
}, []);
```

https://fr.reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect

2021-09-23 07:01 UTC, alexisjanvier commented on src/GameState/index.tsx
> +      const gameState = JSON.parse(e.data)?.gameState as Game;
What happens if there is no data or if the json is incorrectly formatted?

2021-09-23 07:01 UTC, alexisjanvier commented on src/GameState/index.tsx
> +  const initWebSocket = () => {
What happens if the websocket server is not available?

2021-09-23 07:01 UTC, alexisjanvier commented on src/GameState/index.tsx
> +    WS.onerror = (e: any) => {
The `onerror` catches all errors, including connection initialization errors?

2021-09-23 07:53 UTC, arimet commented on src/GameState/index.tsx
> +      const gameState = JSON.parse(e.data)?.gameState as Game;
I added a check in the following PR

2021-09-23 08:01 UTC, arimet commented on src/GameState/index.tsx
> +  const initWebSocket = () => {
You're right, right now I don't have anything to wrestle with. 
In the following PR I added something like: `ws.addEventListener('error', (err) => console.log(err.message));`

2021-09-23 08:35 UTC, alexisjanvier approved these changes
Ok, let's see in the next PR

2021-09-23 08:35 UTC, merged